<?php

use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('regions')->insert([
          ['name' => '札幌'],
          ['name' => '函館'],
          ['name' => '旭川'],
          ['name' => '室蘭'],
          ['name' => '釧路'],
          ['name' => '帯広'],
          ['name' => '北見'],
          ['name' => '青森'],
          ['name' => '八戸'],
          ['name' => '岩手'],
          ['name' => '盛岡'],
          ['name' => '平泉'],
          ['name' => '宮城'],
          ['name' => '仙台'],
          ['name' => '秋田'],
          ['name' => '山形'],
          ['name' => '庄内'],
          ['name' => '福島'],
          ['name' => '会津'],
          ['name' => '郡山'],
          ['name' => 'いわき'],
          ['name' => '水戸'],
          ['name' => '土浦'],
          ['name' => 'つくば'],
          ['name' => '宇都宮'],
          ['name' => '那須'],
          ['name' => 'とちぎ'],
          ['name' => '群馬'],
          ['name' => '前橋'],
          ['name' => '高崎'],
          ['name' => '大宮'],
          ['name' => '川口'],
          ['name' => '所沢'],
          ['name' => '川越'],
          ['name' => '熊谷'],
          ['name' => '春日部'],
          ['name' => '越谷'],
          ['name' => '千葉'],
          ['name' => '成田'],
          ['name' => '習志野'],
          ['name' => '袖ヶ浦'],
          ['name' => '野田'],
          ['name' => '柏'],
          ['name' => '品川'],
          ['name' => '世田谷'],
          ['name' => '練馬'],
          ['name' => '杉並'],
          ['name' => '足立'],
          ['name' => '八王子'],
          ['name' => '多摩'],
          ['name' => '横浜'],
          ['name' => '川崎'],
          ['name' => '湘南'],
          ['name' => '相模'],
          ['name' => '山梨'],
          ['name' => '富士山'],
          ['name' => '新潟'],
          ['name' => '長岡'],
          ['name' => '長野'],
          ['name' => '松本'],
          ['name' => '諏訪'],
          ['name' => '富山'],
          ['name' => '石川'],
          ['name' => '金沢'],
          ['name' => '福井'],
          ['name' => '岐阜'],
          ['name' => '飛騨'],
          ['name' => '静岡'],
          ['name' => '浜松'],
          ['name' => '沼津'],
          ['name' => '伊豆'],
          ['name' => '富士山'],
          ['name' => '名古屋'],
          ['name' => '豊橋'],
          ['name' => '三河'],
          ['name' => '岡崎'],
          ['name' => '豊田'],
          ['name' => '尾張小牧'],
          ['name' => '伊勢志摩']
          ['name' => '一宮'],
          ['name' => '春日井'],
          ['name' => '三重'],
          ['name' => '鈴鹿'],
          ['name' => '滋賀'],
          ['name' => '京都'],
          ['name' => 'なにわ'],
          ['name' => '大阪'],
          ['name' => '和泉'],
          ['name' => '堺'],
          ['name' => '奈良'],
          ['name' => '和歌山'],
          ['name' => '神戸'],
          ['name' => '姫路'],
          ['name' => '鳥取'],
          ['name' => '島根'],
          ['name' => '岡山'],
          ['name' => '倉敷'],
          ['name' => '広島'],
          ['name' => '福山'],
          ['name' => '山口'],
          ['name' => '下関'],
          ['name' => '徳島'],
          ['name' => '香川'],
          ['name' => '愛媛'],
          ['name' => '高知'],
          ['name' => '福岡'],
          ['name' => '北九州'],
          ['name' => '久留米'],
          ['name' => '筑豊'],
          ['name' => '佐賀'],
          ['name' => '長崎'],
          ['name' => '佐世保'],
          ['name' => '熊本'],
          ['name' => '大分'],
          ['name' => '宮崎'],
          ['name' => '鹿児島'],
          ['name' => '奄美'],
          ['name' => '沖縄'],
      ]);
    }
}
