<?php

use Illuminate\Database\Seeder;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('regions')->insert([
          ['code' => 1,'name' => '札幌'],
          ['code' => 2,'name' => '函館'],
          ['code' => 3,'name' => '知床'],
          ['code' => 4,'name' => '苫小牧'],
          ['code' => 5,'name' => '旭川'],
          ['code' => 6,'name' => '室蘭'],
          ['code' => 7,'name' => '釧路'],
          ['code' => 8,'name' => '帯広'],
          ['code' => 9,'name' => '北見'],
          ['code' => 10,'name' => '青森'],
          ['code' => 11,'name' => '弘前'],
          ['code' => 12,'name' => '八戸'],
          ['code' => 13,'name' => '岩手'],
          ['code' => 14,'name' => '盛岡'],
          ['code' => 15,'name' => '平泉'],
          ['code' => 16,'name' => '宮城'],
          ['code' => 17,'name' => '仙台'],
          ['code' => 18,'name' => '秋田'],
          ['code' => 19,'name' => '山形'],
          ['code' => 20,'name' => '庄内'],
          ['code' => 21,'name' => '福島'],
          ['code' => 22,'name' => '会津'],
          ['code' => 23,'name' => '白河'],
          ['code' => 24,'name' => '郡山'],
          ['code' => 25,'name' => 'いわき'],
          ['code' => 26,'name' => '水戸'],
          ['code' => 27,'name' => '土浦'],
          ['code' => 28,'name' => 'つくば'],
          ['code' => 29,'name' => '宇都宮'],
          ['code' => 30,'name' => '那須'],
          ['code' => 31,'name' => 'とちぎ'],
          ['code' => 32,'name' => '群馬'],
          ['code' => 33,'name' => '前橋'],
          ['code' => 34,'name' => '高崎'],
          ['code' => 35,'name' => '大宮'],
          ['code' => 36,'name' => '川口'],
          ['code' => 37,'name' => '所沢'],
          ['code' => 38,'name' => '川越'],
          ['code' => 39,'name' => '熊谷'],
          ['code' => 40,'name' => '春日部'],
          ['code' => 41,'name' => '越谷'],
          ['code' => 42,'name' => '千葉'],
          ['code' => 43,'name' => '松戸'],
          ['code' => 44,'name' => '市川'],
          ['code' => 45,'name' => '船橋'],
          ['code' => 46,'name' => '市原'],
          ['code' => 47,'name' => '成田'],
          ['code' => 48,'name' => '習志野'],
          ['code' => 49,'name' => '袖ヶ浦'],
          ['code' => 50,'name' => '野田'],
          ['code' => 51,'name' => '柏'],
          ['code' => 52,'name' => '江東'],
          ['code' => 53,'name' => '板橋'],
          ['code' => 54,'name' => '葛飾'],
          ['code' => 55,'name' => '品川'],
          ['code' => 56,'name' => '世田谷'],
          ['code' => 57,'name' => '練馬'],
          ['code' => 58,'name' => '杉並'],
          ['code' => 59,'name' => '足立'],
          ['code' => 60,'name' => '八王子'],
          ['code' => 61,'name' => '多摩'],
          ['code' => 62,'name' => '横浜'],
          ['code' => 63,'name' => '川崎'],
          ['code' => 64,'name' => '湘南'],
          ['code' => 65,'name' => '相模'],
          ['code' => 66,'name' => '山梨'],
          ['code' => 67,'name' => '富士山'],
          ['code' => 68,'name' => '新潟'],
          ['code' => 69,'name' => '上越'],
          ['code' => 70,'name' => '長岡'],
          ['code' => 71,'name' => '長野'],
          ['code' => 72,'name' => '松本'],
          ['code' => 73,'name' => '諏訪'],
          ['code' => 74,'name' => '富山'],
          ['code' => 75,'name' => '石川'],
          ['code' => 76,'name' => '金沢'],
          ['code' => 77,'name' => '福井'],
          ['code' => 78,'name' => '岐阜'],
          ['code' => 79,'name' => '飛騨'],
          ['code' => 80,'name' => '静岡'],
          ['code' => 81,'name' => '浜松'],
          ['code' => 82,'name' => '沼津'],
          ['code' => 83,'name' => '伊豆'],
          ['code' => 84,'name' => '富士山'],
          ['code' => 85,'name' => '名古屋'],
          ['code' => 86,'name' => '豊橋'],
          ['code' => 87,'name' => '三河'],
          ['code' => 88,'name' => '岡崎'],
          ['code' => 89,'name' => '豊田'],
          ['code' => 90,'name' => '尾張小牧'],
          ['code' => 91,'name' => '伊勢志摩'],
          ['code' => 92,'name' => '一宮'],
          ['code' => 93,'name' => '春日井'],
          ['code' => 94,'name' => '三重'],
          ['code' => 95,'name' => '四日市'],
          ['code' => 96,'name' => '鈴鹿'],
          ['code' => 97,'name' => '滋賀'],
          ['code' => 98,'name' => '京都'],
          ['code' => 99,'name' => 'なにわ'],
          ['code' => 100,'name' => '大阪'],
          ['code' => 101,'name' => '和泉'],
          ['code' => 102,'name' => '堺'],
          ['code' => 103,'name' => '奈良'],
          ['code' => 104,'name' => '飛鳥'],
          ['code' => 105,'name' => '和歌山'],
          ['code' => 106,'name' => '神戸'],
          ['code' => 107,'name' => '姫路'],
          ['code' => 108,'name' => '鳥取'],
          ['code' => 109,'name' => '島根'],
          ['code' => 110,'name' => '出雲'],
          ['code' => 111,'name' => '岡山'],
          ['code' => 112,'name' => '倉敷'],
          ['code' => 113,'name' => '広島'],
          ['code' => 114,'name' => '福山'],
          ['code' => 115,'name' => '山口'],
          ['code' => 116,'name' => '下関'],
          ['code' => 117,'name' => '徳島'],
          ['code' => 118,'name' => '香川'],
          ['code' => 119,'name' => '高松'],
          ['code' => 120,'name' => '愛媛'],
          ['code' => 121,'name' => '高知'],
          ['code' => 122,'name' => '福岡'],
          ['code' => 123,'name' => '北九州'],
          ['code' => 124,'name' => '久留米'],
          ['code' => 125,'name' => '筑豊'],
          ['code' => 126,'name' => '佐賀'],
          ['code' => 127,'name' => '長崎'],
          ['code' => 128,'name' => '佐世保'],
          ['code' => 129,'name' => '熊本'],
          ['code' => 130,'name' => '大分'],
          ['code' => 131,'name' => '宮崎'],
          ['code' => 132,'name' => '鹿児島'],
          ['code' => 133,'name' => '奄美'],
          ['code' => 134,'name' => '沖縄'],
      ]);
    }
}
